name: Gradle Build

on: [pull_request, push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true