name: JPackage Linux

on:
  release:
    types:
      - prereleased
      - released
      - edited

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jpackage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - uses: softprops/action-gh-release@v1
        with:
          files: build/jpackage/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
